### ISSUE TITLE
开发环境下，自带插件加载不正常 || In the development environment, the built-in plug-in is not loaded normally

### ISSUE THREAD

**Issue by kkqy** [msgbyte/tailchat#124]
我在项目目录下执行
pnpm dev
能正常启动，但是内置的插件都无法使用，
```
插件加载失败:
- com.msgbyte.webview
- com.msgbyte.bbcode
- com.msgbyte.notify
- com.msgbyte.intro
- com.msgbyte.mdpanel
- com.msgbyte.offline-icons
- com.msgbyte.miaolang
```

F12以后，发现这些插件的index.js都是404，开发环境下的http服务默认没有做这些内置插件的路由吗？

---
I execute in the project directory
pnpm dev
It can start normally, but the built-in plug-ins cannot be used.
```
Plugin failed to load:
- com.msgbyte.webview
- com.msgbyte.bbcode
- com.msgbyte.notify
- com.msgbyte.intro
- com.msgbyte.mdpanel
- com.msgbyte.offline-icons
- com.msgbyte.miaolang
```

After F12, I found that the index.js of these plug-ins are all 404. Doesn’t the http service in the development environment do routing for these built-in plug-ins by default?

**Comment by moonrailgun** [comment]
首次执行你需要在`client/web`目录下编译一次插件: `pnpm plugins:all`

**Comment by kkqy** [comment]
> 首次执行你需要在`client/web`目录下编译一次插件: `pnpm plugins:all`

试了一下，在 client/web 执行 pnpm plugins:all 以后还是不行，
我看
client\web\dist\plugins
里已经有这些插件了，但是在项目的pnpm dev下，这些插件还是404

**Comment by kkqy** [comment]
另外 项目根目录下 pnpm dev 对于404也没有做fallback to index处理，每次刷新就404了，必须重新访问http://localhost:11000
子路径下一刷新就404，不知道是不是我哪里漏了步骤，有点不太方便。

**Comment by moonrailgun** [comment]
哦。你开发的话得访问 http://localhost:11011/

**Comment by kkqy** [comment]
> 哦。你开发的话得访问 http://localhost:11011/
> 
> https://tailchat.msgbyte.com/docs/deployment/dev
> 
> oh. If you develop, you have to visit http://localhost:11011/
> 
> https://tailchat.msgbyte.com/docs/deployment/dev

还是有问题，使用http://localhost:11011/访问的话，下面这个文件无法加载，然后所有的历史消息都是”加载中...“
http://127.0.0.1:11011/shepherd.js

**Comment by moonrailgun** [comment]
刷新一下页面看下，消息显示加载中是因为有js没有获取到导致的。

shepherd.js 这个的问题我看下

**Comment by kkqy** [comment]
> 刷新一下页面看下，消息显示加载中是因为有js没有获取到导致的。
> 
> shepherd.js 这个的问题我看下
> 
> Refresh the page and see, the message shows that the loading is because some js has not been obtained.
> 
> Shepherd.js This question I look

是的，应该跟插件有关系，我把bbcode还有那个引导插件从内置插件里删除了，就正常了。

**Comment by kkqy** [comment]
安装自带的插件提示：

```
manager.ts:76  Plugin load error: {pluginName: '@plugins/com.msgbyte.miaolang/reg-1932d888.js', detail: Error: [miao-lang] Cannot load, please checkout your code in miao-lang(undefined).
    at eval (web…}
onPluginLoadError @ manager.ts:76
callModuleLoadError @ config.js:48
eval @ helper.js:291
eval @ helper.js:223
Promise.catch(异步)
requirePlugin @ helper.js:221
loadedModules.<computed>._promise @ helper.js:248
definePlugin @ helper.js:241
(匿名) @ reg-1932d888.js:1
workbox-96b3b901.js:45 workbox Using StaleWhileRevalidate to respond to '/plugins/com.msgbyte.miaolang/miaotrans-197f1af7.js'
workbox-96b3b901.js:45 workbox The request for '/plugins/com.msgbyte.miaolang/miaotrans-197f1af7.js' returned a response that does not meet the criteria for being cached.
helper.js:222  Error: [miao-lang] Cannot load, please checkout your code in miao-lang(undefined).
    at eval (helper.js:159:43)
    at step (helper.js:33:23)
    at Object.eval [as next] (helper.js:14:53)
    at eval (helper.js:8:71)
    at new Promise (<anonymous>)
    at __awaiter (helper.js:4:12)
    at loadDependencyScript (helper.js:131:20)
    at eval (helper.js:199:21)
    at step (helper.js:33:23)
    at Object.eval [as next] (helper.js:14:53)
eval @ helper.js:222
Promise.catch(异步)
requirePlugin @ helper.js:221
eval @ helper.js:260
common.regChatInputAction.label @ index.ts:12
(匿名) @ index.ts:12
eval @ helper.js:273
eval @ helper.js:219
Promise.then(异步)
requirePlugin @ helper.js:218
loadedModules.<computed>._promise @ helper.js:248
definePlugin @ helper.js:241
(匿名) @ index-1996beec.js:1
manager.ts:76  Plugin load error: {pluginName: '@plugins/com.msgbyte.miaolang/index-1996beec.js', detail: Error: [miao-lang] Cannot load, please checkout your code in miao-lang(undefined).
    at eval (web…}
onPluginLoadError @ manager.ts:76
callModuleLoadError @ config.js:48
eval @ helper.js:261
eval @ helper.js:223
Promise.catch(异步)
requirePlugin @ helper.js:221
eval @ helper.js:260
common.regChatInputAction.label @ index.ts:12
(匿名) @ index.ts:12
eval @ helper.js:273
eval @ helper.js:219
Promise.then(异步)
requirePlugin @ helper.js:218
loadedModules.<computed>._promise @ helper.js:248
definePlugin @ helper.js:241
(匿名) @ index-1996beec.js:1
helper.js:222  Error: [miao-lang] Cannot load, please checkout your code in miao-lang(undefined).
    at eval (helper.js:159:43)
    at step (helper.js:33:23)
    at Object.eval [as next] (helper.js:14:53)
    at eval (helper.js:8:71)
    at new Promise (<anonymous>)
    at __awaiter (helper.js:4:12)
    at loadDependencyScript (helper.js:131:20)
    at eval (helper.js:199:21)
    at step (helper.js:33:23)
    at Object.eval [as next] (helper.js:14:53)
eval @ helper.js:222
Promise.catch(异步)
requirePlugin @ helper.js:221
loadedModules.<computed>._promise @ helper.js:248
definePlugin @ helper.js:241
(匿名) @ miaotrans-197f1af7.js:1
manager.ts:76  Plugin load error: {pluginName: '@plugins/com.msgbyte.miaolang/miaotrans-197f1af7.js', detail: Error: [miao-lang] Cannot load, please checkout your code in miao-lang(undefined).
    at eval (web…}
```

**Comment by moonrailgun** [comment]
为啥你这边会有这么多问题。。。你看下是不是这个文件不存在

**Comment by kkqy** [comment]
我来说一下我的步骤，因为浮现这个问题很简单：
1.按照文档里的说明运行 redis、mongo、minio的docker镜像
```
mongodb

docker run -d --name mongo -p 27017:27017 mongo:4

redis

docker run -d --name redis -p 6379:6379 redis

minio

docker run -d \
  -p 19000:9000 \
  -p 19001:9001 \
  --name minio \
  -e "MINIO_ROOT_USER=tailchat" \
  -e "MINIO_ROOT_PASSWORD=com.msgbyte.tailchat" \
  minio/minio server /data --console-address ":9001"
```
2. git clone 这整个项目，然后cd tailchat
3. 先 cd client/web 执行 pnpm plugins:all
4. cd回到tailchat根目录，执行 pnpm dev
5. 访问 http://127.0.0.1:11011 或者 http://localhost:11011 (我开始以为是跨域的原因，所以试了localhost和127.0.0.1问题都在）

然后就是上面后面遇到的问题了：
1. shepherd.js 不存在
2. 消息全是”载入中”，然后我去client\web\src\plugin\builtin.ts 里禁用掉了一堆插件，包括那个bbcode和那个引导插件以后，历史消息显示正常了。而且顺便发现，那个 shepherd.js 其实是那个引导插件加载的js，所以顺带“解决了” shepherd.js的问题
3. 安装喵语插件，能安装成功，但是在输入框那个 + 里面点击“喵言喵语”，一直提示加载中。

总结起来就是，在开发模式下，访问 http://127.0.0.1:11011 ，插件有各种问题。。。

我的主要目的其实是开发插件，因为目前那个插件开发的文档貌似不完整，
发现自带插件import了一些东西文档里没说明。
```
import { regPluginPanelAction } from '@capital/common';
import { regChatInputAction, openModal, Loadable } from '@capital/common';
import { showToasts } from '@capital/common';
import { PortalAdd, PortalRemove, Loadable } from '@capital/component';
```
所以我现在只能参考自带的插件举一反三来写，现在的情况是自带插件在开发环境下都加载不正常，搞得我有点一头雾水。

**Comment by kkqy** [comment]
build出来是没问题的，就是dev开发下插件有问题。

**Comment by moonrailgun** [comment]
我尝试复现一下

**Comment by kkqy** [comment]
已经解决了，之前bbcode有问题，我禁用了，然后开发自己的插件，然后琢磨那个regPluginCardItem的过程中，打开了bbcode，发现又没报错了……所以有点莫名其妙。
