### ISSUE TITLE
机器人无法接收数据 || Robot cannot receive data

### ISSUE THREAD

**Issue by oiov** [msgbyte/tailchat#225]
使用[官方文档](https://tailchat.msgbyte.com/zh-Hans/docs/advanced-usage/openapp/bot)代码创建的机器人：
```js
router.post("/callback", async (ctx) => {
  console.log(ctx);
  const type = ctx.body.type;
  ...
}
```

我增加了一行日志，在频道里@机器人成功触发了callback，日志：
```js
Login...
Server is running on http://localhost:3030
tailchat openapp login success!
{
request: {
method: 'POST',
url: '/callback',
header: {
host: 'tailbot.vmail.dev:443',
'x-real-ip': 'x.x.x.x',
'x-forwarded-for': ''x.x.x.x',
'remote-host': ''x.x.x.x',
'x-host': 'tailbot.vmail.dev:443',
'x-scheme': 'https',
connection: 'upgrade',
'content-length': '461',
'user-agent': 'got (https://github.com/sindresorhus/got)',
'x-tc-payload-type': 'inbox',
'content-type': 'application/json',
'accept-encoding': 'gzip, deflate, br'
}
},
response: {
status: 404,
message: 'Not Found',
header: [Object: null prototype] {}
},
app: { subdomainOffset: 2, proxy: false, env: 'development' },
originalUrl: '/callback',
req: '<original node req>',
res: '<original node res>',
socket: '<original node socket>'
}

TypeError: Cannot read properties of undefined (reading 'type')
at /www/wwwroot/tailchat-bot/index.js:23:25
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:42:32)
at /www/wwwroot/tailchat-bot/node_modules/koa-router/lib/router.js:423:16
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:42:32)
at /www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:34:12
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-router/lib/router.js:428:31)
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:42:32)
at /www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:34:12
at Application.handleRequest (/www/wwwroot/tailchat-bot/node_modules/koa/lib/application.js:186:12)
at Server.handleRequest (/www/wwwroot/tailchat-bot/node_modules/koa/lib/application.js:157:21)
```

补充：
发现请求体中没有数据所以拿不到。机器人的端口是 `http://localhost:3030` 我用 `tailbot.vmail.dev` 做了反代，在机器人的消息回调地址那里就填的是`https://tailbot.vmail.dev/callback`。

但是我用[tailchat-laf-robot](https://tailchat.msgbyte.com/zh-Hans/blog/tailchat-laf-robot)可以正常拿到数据返回，host那些应该配置没问题，难道自部署是有什么差异吗？为什么ctx里没有payload？

---
Bot created using [Official Documentation](https://tailchat.msgbyte.com/zh-Hans/docs/advanced-usage/openapp/bot) code:
```js
router.post("/callback", async (ctx) => {
  console.log(ctx);
  const type = ctx.body.type;
  ...
}
```

I added a line of log. @Robot successfully triggered the callback in the channel. The log:
```js
Login...
Server is running on http://localhost:3030
tailchat openapp login success!
{
request: {
method: 'POST',
url: '/callback',
header: {
host: 'tailbot.vmail.dev:443',
'x-real-ip': 'x.x.x.x',
'x-forwarded-for': ''x.x.x.x',
'remote-host': ''x.x.x.x',
'x-host': 'tailbot.vmail.dev:443',
'x-scheme': 'https',
connection: 'upgrade',
'content-length': '461',
'user-agent': 'got (https://github.com/sindresorhus/got)',
'x-tc-payload-type': 'inbox',
'content-type': 'application/json',
'accept-encoding': 'gzip, deflate, br'
}
},
response: {
status: 404,
message: 'Not Found',
header: [Object: null prototype] {}
},
app: { subdomainOffset: 2, proxy: false, env: 'development' },
originalUrl: '/callback',
req: '<original node req>',
res: '<original node res>',
socket: '<original node socket>'
}

TypeError: Cannot read properties of undefined (reading 'type')
at /www/wwwroot/tailchat-bot/index.js:23:25
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:42:32)
at /www/wwwroot/tailchat-bot/node_modules/koa-router/lib/router.js:423:16
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:42:32)
at /www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:34:12
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-router/lib/router.js:428:31)
at dispatch (/www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:42:32)
at /www/wwwroot/tailchat-bot/node_modules/koa-compose/index.js:34:12
at Application.handleRequest (/www/wwwroot/tailchat-bot/node_modules/koa/lib/application.js:186:12)
at Server.handleRequest (/www/wwwroot/tailchat-bot/node_modules/koa/lib/application.js:157:21)
```

Replenish:
It was found that there was no data in the request body so it could not be obtained. The robot's port is `http://localhost:3030`. I used `tailbot.vmail.dev` for reverse generation. The message callback address of the robot is `https://tailbot.vmail.dev/callback'. `.

But I can use [tailchat-laf-robot](https://tailchat.msgbyte.com/zh-Hans/blog/tailchat-laf-robot) to get the data back normally. The host should be configured with no problem. Is it self-deployment? Is there any difference? Why is there no payload in ctx?

**Comment by oiov** [comment]
我也不知道为什么是404，这是我所有代码：
```js
const { TailchatHTTPClient, stripMentionTag } = require("tailchat-client-sdk");
const Koa = require("koa");
const Router = require("koa-router");

const app = new Koa();
const router = new Router();

const host = "https://im.vmail.dev";
const appId = "---";
const appSecret = "---";

const client = new TailchatHTTPClient(host, appId, appSecret);

// 定义路由
router.get("/", async (ctx) => {
  ctx.body = "Hello, World!";
});

router.post("/callback", async (ctx) => {
  console.log(ctx);
  const type = ctx.body.type;

  if (type === "message") {
    const payload = ctx.body.payload;
    try {
      const message = await client.replyMessage(
        {
          messageId: payload.messageId,
          author: payload.messageAuthor,
          content: payload.messageSnippet,
        },
        {
          groupId: payload.groupId,
          converseId: payload.converseId,
          content: `Your message: ${stripMentionTag(payload.messageSnippet)}`,
        }
      );

      console.log("send message success:", message);
    } catch (err) {
      console.log("send message failed:", err);
    }
  }

  ctx.body = "Bot Callback Page";
});

// 注册路由中间件
app.use(router.routes());
app.use(router.allowedMethods());

// 启动服务
app.listen(3030, () => {
  console.log("Server is running on http://localhost:3030");
});
```

**Comment by moonrailgun** [comment]
you can try to send a post request by yourself at first rather than tailchat.

**Comment by oiov** [comment]
> you can try to send a post request by yourself at first rather than tailchat.

I send a post request to `https://tailbot.vmail.dev/callback` , no request body set, and error log similar to tailchat:

```js
{
request: {
method: 'POST',
url: '/callback',
header: {
host: 'tailbot.vmail.dev:443',
'x-real-ip': 'x.x.x.x',
'x-forwarded-for': 'x.x.x.x',
'remote-host': 'x.x.x.x',
'x-host': 'tailbot.vmail.dev:443',
'x-scheme': 'https',
connection: 'upgrade',
'content-length': '0',
'user-agent': 'PostmanRuntime/7.38.0',
accept: '*/*',
'cache-control': 'no-cache',
'postman-token': 'fd4a2774-cea3-4053-bfcb-bb8b555d75fb',
'accept-encoding': 'gzip, deflate, br'
}
},
response: {
status: 404,
message: 'Not Found',
header: [Object: null prototype] {}
},
app: { subdomainOffset: 2, proxy: false, env: 'development' },
originalUrl: '/callback',
req: '<original node req>',
res: '<original node res>',
socket: '<original node socket>'
}
```

**Comment by moonrailgun** [comment]
looks like your node server not work correct. looks not tailchat's problem
can you try to visit by localhost rather then domain?

**Comment by oiov** [comment]
> looks like your node server not work correct. looks not tailchat's problem can you try to visit by localhost rather then domain?


请问是这样吗？但我似乎无法触发callback
<img width="280" alt="{6EF717B5-9B79-4247-A377-CC9FCBF1D6A5}" src="https://github.com/msgbyte/tailchat/assets/166131050/3ffda5b5-61bc-4fab-9a91-47329d479402">
<img width="257" alt="{D1CEE737-8940-448a-A07E-0C0E049D7502}" src="https://github.com/msgbyte/tailchat/assets/166131050/6dfc8c64-82f4-4e54-8cf9-600bd74f2af0">

**Comment by moonrailgun** [comment]
can you try to trigger request manual first?

**Comment by moonrailgun** [comment]
it your tailchat deploy in local?

**Comment by oiov** [comment]
> is your tailchat deploy in local?

I deployed docker to my server.

**Comment by YInJunWen** [comment]
I encountered the same issue as you. The root cause is that Koa.js requires a middleware to handle the body content when parsing JSON data. If you're unable to resolve this, I recommend using the Express framework. Older versions of Express had the same problem as Koa.js, but in the latest version, they have integrated the solution internally. Therefore, you can use it quite easily and obtain the information after the bot is @-mentioned.
