### ISSUE TITLE
ERROR TypeError : The "this" argument must be an instance of Performance

### ISSUE THREAD

**Issue by quankori** [msgbyte/tailchat#233]
When I run command line `npx pnpm@8 dev` same document setup dev environemnt,  I got a error like:
```
 Request error! TypeError : The "this" argument must be an instance of Performance. Received undefined 
[dev:server] [dev:main]  TypeError: The "this" argument must be an instance of Performance. Received undefined
[dev:server] [dev:main]     at now (node:internal/perf/performance:135:5)
[dev:server] [dev:main]     at Span.start (/Users/k0r1/Documents/Projects/left-curve-be/socket/node_modules/.pnpm/moleculer@0.14.23_patch_hash=ahhlgpfy57fntn2aftq6beaeja_ioredis@4.28.5_nats@1.4.12_redlock@4.2.0/node_modules/moleculer/src/tracing/span.js:84:21)
[dev:server] [dev:main]     at Tracer.startSpan (/Users/k0r1/Documents/Projects/left-curve-be/socket/node_modules/.pnpm/moleculer@0.14.23_patch_hash=ahhlgpfy57fntn2aftq6beaeja_ioredis@4.28.5_nats@1.4.12_redlock@4.2.0/node_modules/moleculer/src/tracing/tracer.js:216:8)
[dev:server] [dev:main]     at Context.startSpan (/Users/k0r1/Documents/Projects/left-curve-be/socket/node_modules/.pnpm/moleculer@0.14.23_patch_hash=ahhlgpfy57fntn2aftq6beaeja_ioredis@4.28.5_nats@1.4.12_redlock@4.2.0/node_modules/moleculer/src/context.js:416:30)
[dev:server] [dev:main]     at ServiceBroker.tracingLocalActionMiddleware (/Users/k0r1/Documents/Projects/left-curve-be/socket/node_modules/.pnpm/moleculer@0.14.23_patch_hash=ahhlgpfy57fntn2aftq6beaeja_ioredis@4.28.5_nats@1.4.12_redlock@4.2.0/node_modules/moleculer/src/middlewares/tracing.js:88:22)
[dev:server] [dev:main]     at Object.actions.<computed> [as rest] (/Users/k0r1/Documents/Projects/left-curve-be/socket/node_modules/.pnpm/moleculer@0.14.23_patch_hash=ahhlgpfy57fntn2aftq6beaeja_ioredis@4.28.5_nats@1.4.12_redlock@4.2.0/node_modules/moleculer/src/service.js:192:13)
[dev:server] [dev:main]     at ApiService.httpHandler (/Users/k0r1/Documents/Projects/left-curve-be/socket/server/packages/sdk/dist/services/lib/moleculer-web/index.js:335:51)
[dev:server] [dev:main]     at Server.<anonymous> (/Users/k0r1/Documents/Projects/left-curve-be/socket/node_modules/.pnpm/engine.io@6.5.2/node_modules/engine.io/build/server.js:668:34)
[dev:server] [dev:main]     at Server.emit (node:events:519:28)
[dev:server] [dev:main]     at Server.emit (node:domain:488:12)
[dev:server] [dev:main]     at parserOnIncoming (node:_http_server:1137:12)
[dev:server] [dev:main]     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) 
[dev:server] [dev:main] Data: undefined
```

**Comment by moonrailgun** [comment]
I think you should use node 18. because the framework not support node 20 yet
